<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.yukthitech</groupId>
		<artifactId>yukthi-autox-parent</artifactId>
		<version>1.0-SNAPSHOT</version>
		<relativePath>../yukthi-autox-parent</relativePath>
	</parent>
	<artifactId>yukthi-autox-all</artifactId>
	<version>3.0.0-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>yukthi-autox-all</name>
	<dependencies>
		<dependency>
			<groupId>com.yukthitech</groupId>
			<artifactId>yukthi-autox-lang</artifactId>
			<version>3.0.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.yukthitech</groupId>
			<artifactId>yukthi-autox-sql</artifactId>
			<version>3.0.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.yukthitech</groupId>
			<artifactId>yukthi-autox-mongo</artifactId>
			<version>3.0.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.yukthitech</groupId>
			<artifactId>yukthi-autox-rest</artifactId>
			<version>3.0.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.yukthitech</groupId>
			<artifactId>yukthi-autox-ui-selenium</artifactId>
			<version>3.0.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.yukthitech</groupId>
			<artifactId>yukthi-autox-webutils</artifactId>
			<version>3.0.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.yukthitech</groupId>
			<artifactId>yukthi-autox-mail</artifactId>
			<version>3.0.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.yukthitech</groupId>
			<artifactId>yukthi-autox-ssh</artifactId>
			<version>3.0.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.yukthitech</groupId>
			<artifactId>yukthi-autox-mock</artifactId>
			<version>3.0.0-SNAPSHOT</version>
		</dependency>
	</dependencies>
</project>
